### ISSUE TITLE
Security Alert in Chrome when trying to download unetbootin

### ISSUE THREAD

**Issue by paulsonnentag** [unetbootin/unetbootin#135]
I get the following warning when I try to download the dmg file  I'm using Chrome 59.0.3071.115 (Official Build) (64-bit)
<img width="827" alt="screen shot 2017-07-25 at 12 44 11" src="https://user-images.githubusercontent.com/650540/28568706-01abccf4-7137-11e7-8ced-87d802382e46.png">

**Comment by qwertychouskie** [comment]
That's weird, is this from the official site?
https://unetbootin.github.io/

**Comment by paulsonnentag** [comment]
Yes, but I just tried it again and I no longer get the warning

**Comment by gkovacs** [comment]
sounds like a bug in chrome's malware detection that google has since fixed (I'm assuming some other malware project was using github as a host and it resulted in all github-hosted releases being erroneously flagged), if this resurfaces for anyone please reopen this issue and I'll see who I can contact at google to fix this. thank you!
