### ISSUE TITLE
Image size

### ISSUE THREAD

**Issue by duanesh** [unetbootin/unetbootin#159]
I create an image to put on a 4Gb USB stick and it works fine.  I want to replicate this so I create an image of the usb stick using dd, rawwrite, Win32DiskImager etc. and the resulting file is 8Gb.  I can write this back to a 4Gb usb stick.  I assume that the actual file size is < 4Gb so this seems to be working.  My question is why would I see this behavior?  I have the usb stick formatted for fat32 so isn't 4G the max size?

**Comment by mquevill** [comment]
The best explanation I can find for this behavior is [this Unix StackExchage question](https://unix.stackexchange.com/a/37590). Essentially, sparse files can report as different sizes, depending on how you are querying their sizes. This is why distros will often specify a minimum USB capacity, instead of having the user guess by how big the .iso appears to be.

FAT32 has a limit of 4 GB for a single file, but the volume can be up to 2 TB.

**Comment by duanesh** [comment]
Ok, thanks for the explanation. 

Yes, I meant to say 4Gb is the max file size.
