### ISSUE TITLE
Arch linux boot failed

### ISSUE THREAD

**Issue by jedi2light** [unetbootin/unetbootin#175]
When crrateing bootable usb with arch linux, unetbootin does not set right LABEL and arch linux can't find /dev/disk/by-label/ARCH_YYYYMM  on boot

**Comment by olivierpotin** [comment]
I am facing same issue with unetbootin from unetbootin-mac-661.dmg using archlinux-2018.06.01-x86_64.iso. The .iso image contains:
partitions:
			0:
				partition-name: ARCH_201806                     
				partition-start: 0
				partition-synthesized: true
				partition-length: 1169408
				partition-filesystems:
				ISO9660: ARCH_201806

As a result, archlinux falls back to an interactive prompt during the boot as not able to mount the proper volume.

**Comment by computerquip** [comment]
Old issue, but the ISO applies a label to the partition and this format tool changes that label. Since the bootable expects a specific label name, it fails to boot. It's such a constant issue they put it as the first step of the Antergos "Create a Working Live USB" guide where they explicitly tell you not to use unetbootin: https://antergos.com/wiki/uncategorized/create-a-working-live-usb/ 

You can just change the partition name to the appropriate name to fix it or use another tool like Rufus.
