### ISSUE TITLE
Remove from boot menu

### ISSUE THREAD

**Issue by ShockedCoder** [unetbootin/unetbootin#279]
I didn't know that unetbootin makes a boot menu instead of just installing it to a drive, and I want to remove it. 
Taken from `neofetch`:
```
OS: Kubuntu 20.10 ( formerly PopOS 20.04, but changed to this when updated )
Kernel: 5.8.0-7625-generic
DE: Plasma
CPU: Intel i9-9900K (16) @ 5.000GHz
GPU: NVIDIA GeForce RTX 2080 Ti Rev. A
```
I've tried to search for a method, but only found methods used on windows

**Comment by gkovacs** [comment]
You probably chose the Hard Disk install mode instead of the USB install mode? I thought re-running the executable will show a prompt where you can uninstall it. If not, then you can use a GRUB menu editor to remove the entry, there's apparently a nice GUI for it described at https://tipsonubuntu.com/2018/03/11/install-grub-customizer-ubuntu-18-04-lts/
