### ISSUE TITLE
release 613 doesn’t work with Fedora 22

### ISSUE THREAD

**Issue by ousia** [unetbootin/unetbootin#56]
unetbootin only displays an empty window.

Error message is the following:

```
]$ su -c unetbootin
Password: 
Qt: Session management error: None of the authentication protocols specified are supported
X Error: BadAccess (attempt to access private resource denied) 10
  Extension:    130 (MIT-SHM)
  Minor opcode: 1 (X_ShmAttach)
  Resource id:  0x13e
X Error: BadShmSeg (invalid shared segment parameter) 128
  Extension:    130 (MIT-SHM)
  Minor opcode: 3 (X_ShmPutImage)
  Resource id:  0x1c0000a
X Error: BadShmSeg (invalid shared segment parameter) 128
  Extension:    130 (MIT-SHM)
  Minor opcode: 3 (X_ShmPutImage)
  Resource id:  0x1c0000a
```

Is this a missing dependency?

**Comment by ousia** [comment]
The reason seems to be explained [here](https://bugzilla.redhat.com/show_bug.cgi?id=1236528#c4).

Any chance of having a patch for release 613?

 Sorry, but packaging changed too much in latest release. This is why I ask for a patch for an older release.

**Comment by gkovacs** [comment]
this sounds rather problematic indeed. I don't know enough about policykit to implement this unfortunately, so if anyone has experience with policykit, any patches would be very welcome.

**Comment by gkovacs** [comment]
dug into this further, turns out launching with

sudo QT_X11_NO_MITSHM=1 unetbootin

and providing a policykit policy file will fix the issue. if you are familiar with debian or arch linux packaging, the version in the archlinux repositories as well as my own PPA https://launchpad.net/~gezakovacs/+archive/ubuntu/ppa incorporate that fix (if all you need is the policy file, it is at https://github.com/unetbootin/unetbootin/blob/master/src/unetbootin/org.unetbootin.pkexec.unetbootin.policy )

**Comment by LucaFranceschini** [comment]
> [...] the version in the archlinux repositories [...] incorporate that fix

I don't think it does, I'm experiencing the same issue on Arch.
